src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModel.java
src/main/java/org/jboss/tools/intellij/openshift/utils/ExecHelper.java

Fix UI update when new project is created

---

README.md
src/main/resources/META-INF/plugin.xml

Removed IntelliJ from branding

---

src/main/java/org/jboss/tools/intellij/openshift/utils/ExecHelper.java

Prevent terminal auto close

---

Jenkinsfile
build.gradle
gradle.properties

Add Jenkinsfile

---

Jenkinsfile

Fix build number substitution

---

Jenkinsfile

Fix distribution regexp

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoTest.java

Skip ITs not supported by odo

---

src/main/resources/tools.json

Switch to odo 0.0.19

---

Jenkinsfile
build.gradle
gradle.properties

Update for publishing

---

Jenkinsfile
build.gradle
gradle.properties

Use token to publish

---

src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigHelper.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoConfig.java
src/test/java/org/jboss/tools/intellij/openshift/utils/OdoConfigTest.java
src/test/resources/odo-config-test.yaml

Adapt to new Odo config file

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java

Rewrote the notification text remove algorithm

---

src/main/resources/tools.json

Switch to odo 0.0.20

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java

Change plugin folder

---

src/main/resources/META-INF/plugin.xml

Change layout for better rendering on plugins.jetbrains.com

---

build.gradle

Switch to gradle plugin 0.0.4

---

gradle.properties

Prepare 0.0.1

---

gradle.properties

Bump to 0.0.2

---

src/main/java/org/jboss/tools/intellij/openshift/utils/ExecHelper.java

Implement workaround for 2018.3

---

src/main/java/org/jboss/tools/intellij/openshift/utils/ExecHelper.java

Apply workaround for 2018.3 to 2019.x as 2019.1 EAP as the same issue

---

gradle.properties

Prepare 0.0.2

---

src/main/java/org/jboss/tools/intellij/openshift/utils/ExecHelper.java

Fix CRLF issues for Macos

---

src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModel.java
src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigHelper.java

Fix wrong Kube config parsing error

---

src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java

Cluster not in the tree was not getting correct icon

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateURLAction.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/URLNode.java
src/main/java/org/jboss/tools/intellij/openshift/ui/url/CreateURLDialog.form
src/main/java/org/jboss/tools/intellij/openshift/ui/url/CreateURLDialog.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java

Support multi URLs creation

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateURLAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/url/DeleteURLAction.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/resources/META-INF/plugin.xml
src/test/java/org/jboss/tools/intellij/openshift/actions/ActionTest.java
src/test/java/org/jboss/tools/intellij/openshift/actions/url/DeleteURLActionTest.java

Add support for delete URL action

---

src/main/java/org/jboss/tools/intellij/openshift/actions/component/OpenInBrowserAction.java
src/test/java/org/jboss/tools/intellij/openshift/actions/component/OpenInBrowserActionTest.java

Implement Open In Browser action on URLs

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoTest.java
src/main/java/org/jboss/tools/intellij/openshift/KubernetesLabels.java
src/main/java/org/jboss/tools/intellij/openshift/actions/service/DescribeServiceAction.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/resources/META-INF/plugin.xml
src/test/java/org/jboss/tools/intellij/openshift/actions/service/DescribeServiceActionTest.java

Implement service describe command

---

src/main/java/org/jboss/tools/intellij/openshift/ui/cluster/LoginDialog.form

Login dialog should be expanded

---

src/main/resources/tools.json

Fix download URLs to reflect new GitHub organization

---

src/main/java/org/jboss/tools/intellij/openshift/utils/ExecHelper.java

Fixes #76
Align odo output for Linux OSes
See #76 
Create a component and push on a Linux machine and observe odo output

Fix odo output aligment on Linux OSes

---

src/main/resources/tools.json

Fixes #80
Switch to odo 1.0.0
fixes #???

Switch to odo 1.0.0 release

---

.travis.yml
gradle/wrapper/gradle-wrapper.properties

Update Gradle version

---

src/main/resources/META-INF/plugin.xml

Update plugin.xml for 0.1.0

---

src/main/java/org/jboss/tools/intellij/openshift/Constants.java
src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleAction.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java
src/main/resources/META-INF/plugin.xml

Fixes #84
Fixes #88
Fixes OCP4 console URLs
Log in an OCP4 cluster and Open Console Dashboard action

Add support for OCP4 console

---

gradle.properties

Prepare for 0.1.0

---

src/main/resources/META-INF/plugin.xml

correct an error reported by intellij
fixes #93 
load project in intellij and verify that no errors are displayed for ApplicationTreeModel and ClustersTreeModel

corrected required intellij version to 181.3741.2

---

src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModel.java

allow compilation using java 11
fixes #99

Allow compiling with java 11 (#99)

---

build.gradle

specifies sourceCompatibility and targetCompatibility

specified sourceCompatibility, targetCompatibility

---

gradle.properties

Bump to 0.1.1

---

src/main/resources/META-INF/plugin.xml

Signed-off-by: Andre Dietisheim <adietish@redhat.com>
moves the "Delete" to the end of the Explorer ctx menu
fixes #116

moved "Delete" to the end of the explorer ctx menu (#116)

---

src/main/java/org/jboss/tools/intellij/openshift/tree/ClustersTreeModel.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModel.java
src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigHelper.java
src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigWatcher.java

Signed-off-by: Andre Dietisheim <adietish@redhat.com>
fixes #102 
1. ASSERT: have a cluster with a project
1. EXEC: Logout of the cluster
1. EXEC: Log in again with a new token (that you can retrieve in the web-ui)
Result:
Nothing happens, the tree is not refreshed, you still see the "Please log in to the cluster"  as a child node to the cluster node in the explorer
Expected Result:
The tree should display the project as a child node of your cluster (and replace the "Please log in to the cluster").

Also refresh when token is changing.

---

README.md
gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.1.1

---

gradle.properties

Bump to 0.1.2

---

src/main/java/org/jboss/tools/intellij/openshift/tree/ClustersTreeModel.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModel.java
src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigWatcher.java
src/test/java/org/jboss/tools/intellij/openshift/utils/ConfigWatcherTest.java

added ConfigWatcherTest, refactored to allow such unit test

impl'd ConfigWatcherTest

---

src/main/resources/tools.json

Switch to odo release 1.0.2
fixes #139

Switch to odo 1.0.2

---

README.md

Fixed odo link
Fixed Readme link
fixes #139

Switch to odo 1.0.2 - fixed readme link

---

README.md
src/main/java/org/jboss/tools/intellij/openshift/Constants.java
src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/SetCurrentClusterAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugNodeJSComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/tree/ClustersTreeModel.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigHelper.java
src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigWatcher.java

first improvement for fixing issue.
fixes #147 
try with a windows home folder located in a network drive.

Adding more log and fix cluster view 

---

src/main/resources/tools.json

update odo tool to newer version
fixes #151 

issue #151: switch to odo 1.0.3

---

src/main/resources/tools.json

Switch to odo 1.1.0

---

src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModel.java

Signed-off-by: Stéphane Bouchet <sbouchet@redhat.com>
fix refresh issue.
fixes #160 
switch context using action

#160: fix refresh when user use 'set current' action 

---

README.md
gradle.properties

Prepare for 0.2.0

---

src/main/java/org/jboss/tools/intellij/openshift/actions/TreeAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/LoggedInClusterAction.java

Fix Error message dialog
fixes #112 
see original issue

#112: Fix NPE

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliCatalogTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliProjectTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliServiceTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
src/main/java/org/jboss/tools/intellij/openshift/Constants.java
src/main/java/org/jboss/tools/intellij/openshift/actions/application/DeleteApplicationAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/ListServicesAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateURLAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/ImportComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkServiceAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/PushComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/service/DescribeServiceAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/service/LinkComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/storage/CreateStorageAction.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationNode.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ComponentNode.java
src/main/java/org/jboss/tools/intellij/openshift/utils/ExecHelper.java
src/main/java/org/jboss/tools/intellij/openshift/utils/NetworkUtils.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliFactory.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java
src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java

- Use proxy selector when downloading odo
- Setup proxy related env variables when launching odo
Fixes #149
Fixes #69
Replaces #150
Contributions from @doublefx
fixes #???

Proxy support

---

src/main/java/org/jboss/tools/intellij/openshift/actions/TreeAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/ListServicesAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/LoggedInClusterAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/LoggedOutClusterAction.java

Fixing NPE when interacting with the explorer tree.
fixes #171

#171: fix NPE

---

src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModel.java

Fixes #173
Fixes #182
fixes #???

Refresh VFS when loading a new module

---

gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.2.1

---

src/main/resources/META-INF/plugin.xml

Change vendor to make plugin part of the Red Hat organization

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
src/main/java/org/jboss/tools/intellij/openshift/Constants.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

Removed the default sleep time and rely on the odo debug status.
fixes #144

#144: improve odo debug synchronization

---

src/main/resources/tools.json

updated odo to latest version
fixes #192

#192: updated odo to 1.1.3

---

gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.2.2

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

Fixes #173
See https://github.com/openshift/odo/issues/3070 on how to reproduce the case
fixes #???

Fix NPE while processing the URL list

---

gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.2.3

---

gradle.properties
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/resources/META-INF/plugin.xml

Prepare for 0.2.4

---

README.md

Signed-off-by: Mohit Suman <mohit.skn@gmail.com>
Replace OpenShift Do tagline with odo.
fixes #205

replace OpenShift Do tagline with odo

---

.github/workflows/validate_IJ_versions.yml
build.gradle
gradle.properties
src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugComponentAction.java
src/main/resources/META-INF/plugin.xml

Set up workflow for IJ validation
fixes #207

created validate workflow

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ServiceTemplatesDeserializer.java
src/main/resources/tools.json

#209 : update to odo 1.2.2

---

gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.2.5

---

src/main/resources/tools.json

Switch to Odo 1.2.3

---

.travis.yml
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliCatalogTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceAction.java
src/main/java/org/jboss/tools/intellij/openshift/ui/service/CreateServiceDialog.form
src/main/java/org/jboss/tools/intellij/openshift/ui/service/CreateServiceDialog.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ServiceTemplate.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ServiceTemplatesDeserializer.java

Fixes #188
Allow to choose plan when creating service
Fixes #188
Use the create service wizard

Implement plan list for Service creation

---

src/main/resources/META-INF/plugin.xml

Update contact email

---

gradle.properties
src/main/resources/META-INF/plugin.xml

Prepare for 0.3.0

---

.github/workflows/validate_IJ_versions.yml

Add IntelliJ 2020.2

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentTypesDeserializer.java
src/main/resources/tools.json

Switch to Odo 1.2.5

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentDescriptorsDeserializer.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentTypesDeserializer.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ServiceTemplatesDeserializer.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/StoragesDeserializer.java

Code smells

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliFactory.java
src/main/resources/tools.json

#221: switch to odo 1.2.6

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/url/CreateURLAction.java
src/main/java/org/jboss/tools/intellij/openshift/ui/url/CreateURLDialog.form
src/main/java/org/jboss/tools/intellij/openshift/ui/url/CreateURLDialog.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentDeserializer.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/JSonParser.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

Support create URL for devfile components
fixes #232

Support create URL for devfile components

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
src/main/java/org/jboss/tools/intellij/openshift/Constants.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentDialogStep.java
src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentModel.java
src/main/java/org/jboss/tools/intellij/openshift/ui/component/ModuleSelectionDialog.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

#246: Add support for local project devfile 

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliApplicationTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugJavaComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugNodeJSComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/ui/url/CreateURLDialog.java
src/main/java/org/jboss/tools/intellij/openshift/utils/ExecHelper.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/JSonParser.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

Debug support for Java and NodeJS devfile components
fixes #231

Support debug for devfile based components

---

src/main/java/org/jboss/tools/intellij/openshift/ui/cluster/LoginDialog.form
src/main/java/org/jboss/tools/intellij/openshift/ui/cluster/LoginDialog.java
src/main/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtils.java
src/test/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtilsTest.java

Implemented button to paste login command from openshift cluster
fixes #39

Issue 39 : implement paste login from OpenShift Cluster

---

.github/workflows/ci.yml

added step to publish test results to avoid scrolling logs.

---

.github/workflows/ci.yml
.github/workflows/validate_IJ_versions.yml
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java

Use helper from intellij-common
Use 2020.3 as default
fixes #???

Add 2020.3

---

.github/workflows/ci.yml
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
src/it/projects/springboot-rest/.gitignore
src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkServiceAction.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationNode.java
src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentDialogStep.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/resources/tools.json
src/test/java/org/jboss/tools/intellij/openshift/actions/ActionTest.java

update odo to latest 2.0.3
fixes #227

Update to odo 2.0.3

---

README.md
build.gradle
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

refactor code and bump fabric8 client to 5.0.0
fixes #266

#266: refactor code after bumping fabric8 client version

---

.github/workflows/ci.yml
.github/workflows/publish_reports.yml
.github/workflows/sonar.yml
build.gradle

Fixed test reports checks and sonar checks on PR and pushes
fixes #279

fix test and sonar workflows

---

build.gradle
src/main/resources/tools.json

update to latest odo version
fixes #276

#276: update to odo 2.0.4

---

build.gradle

update intellij-common to 0.0.2

---

.github/workflows/ci.yml
.github/workflows/sonar.yml

SonarCloud does not correctly analyze PRs using workflow_run.
fixes #???

Fix PR analysis by Sonar

---

build.gradle
src/main/java/org/jboss/tools/intellij/openshift/validation/DevfileJsonSchemaFileProvider.java
src/main/java/org/jboss/tools/intellij/openshift/validation/DevfileJsonSchemaProviderFactory.java
src/main/resources/META-INF/plugin-json.xml
src/main/resources/META-INF/plugin.xml
src/main/resources/schemas/devfile.json
src/test/java/org/jboss/tools/intellij/openshift/validation/DevfileSchemasTest.java
src/test/resources/devfiles/java-quarkus.yaml

feat: Provides devfile code assist and validation

---

src/main/resources/tools.json

refactor: update odo to 2.0.5

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliServiceTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/ImportComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/ui/cluster/LoginDialog.form
src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentDialogStep.form
src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentDialogStep.java
src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentModel.java
src/main/java/org/jboss/tools/intellij/openshift/utils/ProjectUtils.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/DevfileComponentType.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/JSonParser.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

propose starters when the selected context is empty
fixes #247 
Create an empty folder and select it when creating a new component.

feat: support starters

---

.github/workflows/conventionalCheck.yml
.github/workflows/release.yml

chore: adopt conventional commits

---

.github/workflows/ci.yml
.github/workflows/sonar.yml

build: Fix sonar report

---

src/main/resources/tools.json

refactor: update to odo 2.0.7

---

.github/workflows/ci.yml
.github/workflows/validate_IJ_versions.yml
Jenkinsfile

chore: switch branch to main

---

Jenkinsfile

chore: add mailer on build failures

---

src/main/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtils.java
src/test/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtilsTest.java

fix: Paste credentials from OCP4 does not work

---

src/main/resources/tools.json

fix: odo downloaded even if found on PATH

---

.github/workflows/release.yml
build.gradle

chore: Fix ZIP file name in release workflow

---

src/main/java/org/jboss/tools/intellij/openshift/ui/cluster/LoginDialog.form
src/main/java/org/jboss/tools/intellij/openshift/ui/cluster/LoginDialog.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

hide chars for token field
fixes #313

fix: hide token chars

---

USAGE_DATA.md
build.gradle
src/main/java/org/jboss/tools/intellij/openshift/telemetry/TelemetryService.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

fix: Add cluster information in telemetry login information

---

build.gradle
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliApplicationTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliProjectTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliRegistryTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliServiceTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/DevfileRegistryComponentTypeNode.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ParentableNode.java
src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentDialogStep.java
src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentModel.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/DevfileComponentType.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/JSonParser.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java
src/main/resources/tools.json

feat: Support odo 2.2

---

build.gradle

chore: Use intellij-common 1.2.1

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliProjectTest.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

feat: Application Explorer should use the current namespace

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

fixes NPE when sending telemetry error. 
fixes #???

chore: fix telemetry

---

src/main/java/org/jboss/tools/intellij/openshift/actions/OdoAction.java

fix: Context menus are failing

---

gradle.properties
src/main/resources/META-INF/plugin.xml

chore: Prepare for 0.8.1

---

.github/workflows/validate_IJ_versions.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

chore: Add 2021.2

---

.github/workflows/validate_IJ_versions.yml
build.gradle

chore: Run plugin verifier in workflow

---

build.gradle

fix: bumped telemetry to 0.2.18 (#345)

---

gradle.properties
src/main/resources/META-INF/plugin.xml

chore: Prepare for 0.8.2

---

.github/workflows/validate_IJ_versions.yml
build.gradle
src/test/java/org/jboss/tools/intellij/openshift/validation/DevfileSchemasTest.java

build: Add IntelliJ 2021.3

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliServiceTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
src/main/java/org/jboss/tools/intellij/openshift/Constants.java
src/main/java/org/jboss/tools/intellij/openshift/actions/url/CreateURLAction.java
src/main/java/org/jboss/tools/intellij/openshift/ui/url/CreateURLDialog.form
src/main/java/org/jboss/tools/intellij/openshift/ui/url/CreateURLDialog.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

update create URL dialog to add extra host parameter when cluster is pure kubenetes.
fixes #361

feat: enable create URL for kubernetes cluster

---

src/main/java/org/jboss/tools/intellij/openshift/utils/ProjectUtils.java

fix: create component was no op on Rider

---

build.gradle
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java

chore: bump alizer to 0.1.0 release

---

src/main/resources/tools.json

fix: Migrate to odo 2.5.0

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ServiceTemplatesDeserializer.java
src/test/java/org/jboss/tools/intellij/openshift/utils/odo/ServiceTemplateRequiredTest.java
src/test/resources/service-template-required-test.json

fix: add support for required CRDs in operators

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ServiceTemplatesDeserializer.java
src/test/java/org/jboss/tools/intellij/openshift/utils/odo/ServiceTemplateRequiredTest.java

fix: skip operators that don't implement Kubernetes API

---

src/main/resources/tools.json

fix: typo in odo version

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
src/main/java/org/jboss/tools/intellij/openshift/telemetry/TelemetryService.java
src/main/java/org/jboss/tools/intellij/openshift/ui/cluster/LoginDialog.java
src/main/java/org/jboss/tools/intellij/openshift/ui/sandbox/SandboxLoginPage.java
src/main/java/org/jboss/tools/intellij/openshift/ui/sandbox/SandboxModel.java
src/main/java/org/jboss/tools/intellij/openshift/ui/sandbox/SandboxProcessor.java
src/main/java/org/jboss/tools/intellij/openshift/ui/sandbox/SandboxWorkflowPage.java
src/test/java/org/jboss/tools/intellij/openshift/actions/ActionTest.java
src/test/java/org/jboss/tools/intellij/openshift/ui/sandbox/SandboxProcessorTest.java

adding telemetry to devsandbox workflow
fixes #376

feat: add telemetry to Devsandbox workflow

---

.github/workflows/validate_IJ_versions.yml
src/main/resources/META-INF/plugin.xml

fix: no browser shown for devsandbox login

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentDeserializer.java
src/test/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentDeserializerTest.java
src/test/resources/components-test.json

fix: Non odo components are not visible

---

build.gradle

fix CVE issue detected by snyk
fixes #391

chore(deps): update to fabric8 openshift 5.7.4

---

build.gradle
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java

chore(deps): update to commons-compress 1.21

---

.github/workflows/validate_IJ_versions.yml
src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java
src/test/java/org/jboss/tools/intellij/openshift/ui/widgets/JsonSchemaWidgetTest.java
src/test/java/org/jboss/tools/intellij/openshift/validation/DevfileSchemasTest.java

build: Add IntelliJ 2022.1

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
src/main/resources/tools.json

chore(deps): update to odo 2.5.1

---

gradle.properties
src/main/resources/META-INF/plugin.xml

chore(skip-release): Prepare for 0.10.0

---

src/main/resources/tools.json

fix: odo 2.5.1 extraction is broken on Windows and MacOS

---

build.gradle

fix: Use io.undertow:undertow-core:2.2.11.Final

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
src/main/java/org/jboss/tools/intellij/openshift/KubernetesLabels.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/DeleteComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/ImportComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/PushComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/UndeployComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentDeserializer.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentInfo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentKind.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/JSonParser.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

fix: Show delete command for non Odo components

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

fix: NPE in telemetry

---

build.gradle
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

Signed-off-by: Andre Dietisheim <adietish@redhat.com>
fixes #424 
depends on https://github.com/redhat-developer/intellij-common/pull/149

chore: bumped openshift-client 5.12.2 & intellij-common 1.7.1 & ij-kubernetes 0.5.1.148 (#424)

---

build.gradle
src/main/resources/tools.json

fix: NPE while displaying tree 

---

gradle.properties
src/main/resources/META-INF/plugin.xml

chore(skip-release): Prepare for 0.11.0

---

.github/workflows/validate_IJ_versions.yml

build: Add IntelliJ 2022.2

---

.github/ISSUE_TEMPLATE/Bug.md
.github/ISSUE_TEMPLATE/Enhancement.md
.github/ISSUE_TEMPLATE/Feature.md
.github/workflows/release.yml
README.md
USAGE_DATA.md
src/main/java/org/jboss/tools/intellij/openshift/Constants.java
src/main/resources/META-INF/plugin.xml

feat: Rename plugin to OpenShift Toolkit

---

src/main/resources/META-INF/plugin.xml

fix(skip-release): Comment out service related actions

---

src/main/java/org/jboss/tools/intellij/openshift/utils/ProjectUtils.java

fix: Can't use starter with empty IJ projects/module

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

fix: Project tree item is not removed after project is deleted

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

fix: Open Console Dashboard menu opens wrong URL

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

fix: Cannot log in to the cluster using username and password

---

gradle.properties
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java
src/main/resources/META-INF/plugin.xml

chore(skip-release): Prepare for 1.0.0

---

build.gradle

build: Bump telemetry to 0.0.3.33

---

src/main/resources/tools.json

fix: Integrate odo ARM64 binaries (MacOS, Linux)

---

build.gradle

chore: bumped openshift-client to 5.12.4 (#471)

---

src/main/java/org/jboss/tools/intellij/openshift/WindowToolFactory.java

chore: replaced disposable (was: project) & removed reflective buildModel (#475)

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java

build: Use staging registry in integration tests

---

src/main/resources/tools.json

fix: Switch to odo 3.2.0

---

src/main/java/org/jboss/tools/intellij/openshift/actions/url/OpenInBrowserAction.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/JSonParser.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/URL.java
src/main/resources/tools.json
src/test/java/org/jboss/tools/intellij/openshift/utils/odo/JsonParserTest.java
src/test/resources/describe-component-deploy-kubernetes.json
src/test/resources/describe-component-deploy-openshift.json
src/test/resources/describe-component-dev.json

feat: Add URL for deployed components

---

build.gradle

build: Can't start IDE from gradle because of linkage error

---

src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/FeatureComponentAction.java

fix: Unify dev and debug actions

---

gradle.properties
src/main/resources/META-INF/plugin.xml
src/main/resources/tools.json

chore(skip-release): Prepare for 1.1.0

---

build.gradle
src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliCatalogTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/FeatureComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/ShowLogComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java

chore: bump to kubernetes-client 6.4.0 (#496)

---

.github/workflows/IJ-latest.yml
.github/workflows/validate_IJ_versions.yml

adds IU-2023.1 to verifications, adds a periodic check against LATEST-EAP-SNAPSHOT

chore: updated workflows (IJ, IJ-latest)

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliFactoryTest.java
src/main/resources/tools.json

fix: Switch to odo 3.9.0

---

build.gradle

fixes #???
* updated intellij-common to latest 1.9.1
* updated intellij-redhat-telemetry to latest 1.0.0

chore: bumped intellij-common, intellij-redhat-telemetry

---

src/main/resources/tools.json
src/test/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentDescriptorTest.java
src/test/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentDeserializerTest.java
src/test/resources/component-descriptor-test.json
src/test/resources/components-test.json

Update to latest odo
fixes #543

fix: Switch to odo 3.10.0

---

src/main/resources/META-INF/plugin.xml
src/main/resources/tools.json

Switch to odo 3.11.0
fixes #550

fix: Switch to odo 3.11.0

---

src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java
src/test/java/org/jboss/tools/intellij/openshift/ui/widgets/JsonSchemaWidgetTest.java
src/test/java/org/jboss/tools/intellij/openshift/validation/DevfileSchemasTest.java

fix: fix test compilation failures for next EAP

---

build.gradle

Added dependency on Gson library (2.9.0) which is needed for running integration UI tests.
fixes https://github.com/redhat-developer/intellij-common-ui-test-library/issues/162

build: Added dependency on gson (2.9.0) for UI tests

---

src/main/resources/tools.json

See https://github.com/redhat-developer/odo/releases/tag/v3.12.0
fix #570

fix: Update odo to 3.12.0

---

.github/workflows/validate_IJ_versions.yml

adds validation against IC-2023.2

chore: validated against IC-2023.2, too

---

src/main/resources/tools.json

See https://github.com/redhat-developer/odo/releases/tag/v3.13.0

fix: Update odo to 3.13.0

---

src/main/java/org/jboss/tools/intellij/openshift/actions/NodeUtils.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/ImportComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkServiceAction.java
src/test/java/org/jboss/tools/intellij/openshift/actions/ActionTest.java
src/test/java/org/jboss/tools/intellij/openshift/actions/component/DeleteComponentActionTest.java
src/test/java/org/jboss/tools/intellij/openshift/actions/component/DescribeComponentActionTest.java
src/test/java/org/jboss/tools/intellij/openshift/actions/component/LinkComponentActionTest.java
src/test/java/org/jboss/tools/intellij/openshift/actions/component/LinkServiceActionTest.java

fix: Link Service action is only visible for components with a context (#552)

---

src/main/resources/tools.json

See https://github.com/redhat-developer/odo/releases/tag/v3.14.0

fix: Update odo to 3.14.0

---

src/main/resources/tools.json

See https://github.com/redhat-developer/odo/releases/tag/v3.15.0

fix: Update odo to 3.15.0

---

build.gradle
gradle.properties

chore: bump to latest IC version

---

.github/workflows/ci.yml
.github/workflows/integration_tests.yml

chore: extract integration tests in their own workflow

---

.github/workflows/integration_tests.yml

chore: publish tests results

---

build.gradle
src/it/java/org/jboss/tools/intellij/openshift/utils/OdoCluster.java
src/it/java/org/jboss/tools/intellij/openshift/utils/helm/Charts.java
src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliInstallTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliListTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliSearchTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/helm/OpenHelmChartsAction.java
src/main/java/org/jboss/tools/intellij/openshift/utils/helm/Helm.java
src/test/java/org/jboss/tools/intellij/openshift/actions/ActionTest.java
src/test/java/org/jboss/tools/intellij/openshift/actions/helm/OpenHelmChartsActionTest.java
src/test/java/org/jboss/tools/intellij/openshift/actions/helm/UninstallReleaseActionTest.java
src/test/java/org/jboss/tools/intellij/openshift/ui/helm/ChartVersionsTest.java
src/test/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentDescriptorTest.java
src/test/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentDeserializerTest.java

test: added helm cli integration tests

---

src/main/java/org/jboss/tools/intellij/openshift/actions/helm/UninstallReleaseAction.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ChartReleaseNode.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/DescriptorFactory.java
src/main/java/org/jboss/tools/intellij/openshift/ui/helm/ChartIcons.java

fix: display helm chart icon for releases (#626)

---

build.gradle
src/main/java/org/jboss/tools/intellij/openshift/tree/application/DescriptorFactory.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

fixes #630 
depends on https://github.com/redhat-developer/intellij-common/pull/204

fix: dont npe when no kubeconfig/current context (#630)

---

src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
src/main/java/org/jboss/tools/intellij/openshift/utils/KubernetesClientExceptionUtils.java

fix: display 'plz login' also when forbidden (#631)

---

.github/workflows/ci.yml
.github/workflows/integration_tests.yml
.github/workflows/sonar.yml

chore: fix sonar workflow

---

src/main/java/org/jboss/tools/intellij/openshift/actions/HelmAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/NodeUtils.java
src/main/java/org/jboss/tools/intellij/openshift/actions/helm/UninstallReleaseAction.java
src/main/java/org/jboss/tools/intellij/openshift/utils/helm/Helm.java
src/main/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCli.java

feat: allow to uninstall several chart releases at once (#653)

---

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

refactor: use stateful openshift client instead of ad hoc (#664)

---

src/it/java/org/jboss/tools/intellij/openshift/test/ui/common/CreateComponentFixture.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/DevOnPodmanComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/AccountService.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/AccountStatus.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/DefaultTokenProvider.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/LoginProvider.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/LoginResponse.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/OAuthCoreConstants.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/OAuthUtils.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/exception/OAuthConfigurationException.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/exception/OAuthException.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/exception/OAuthLoginException.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/exception/OAuthRefreshException.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/model/Account.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/model/AccountModel.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/model/AuthorizationServer.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/model/IAccount.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/model/IAccountModel.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/model/IAuthorizationServer.java
src/main/java/org/jboss/tools/intellij/openshift/oauth/ui/DefaultLoginProvider.java
src/main/java/org/jboss/tools/intellij/openshift/ui/registry/CreateRegistryDialog.java
src/main/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtils.java
src/test/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtilsTest.java

docs: fix headers

---

src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/RefreshAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/FeatureComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/component/ShowLogComponentAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/helm/OpenHelmChartsAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/project/ChangeActiveProjectAction.java

fix: avoid fatal IDE error when tree is refreshing (#690)

---

src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
src/main/java/org/jboss/tools/intellij/openshift/utils/KubernetesClientExceptionUtils.java
src/test/java/org/jboss/tools/intellij/openshift/utils/KubernetesClientExceptionUtilsTest.java

fix: report 'cluster unreachable' instead of 'failed to list secrets' (#682)

---

src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliEnvTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/helm/OpenHelmChartsAction.java
src/main/java/org/jboss/tools/intellij/openshift/ui/helm/ChartPanels.java
src/main/java/org/jboss/tools/intellij/openshift/ui/helm/ChartsDialog.java
src/main/java/org/jboss/tools/intellij/openshift/ui/helm/InstallPanel.java
src/main/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCli.java

feat: show current project when installing helm chart (#613)

---

.github/workflows/nightly.yml
.github/workflows/release.yml

fix(skip-release): fix SHA1 for gradle actions

---

src/main/java/org/jboss/tools/intellij/openshift/actions/project/CreateProjectAction.java

fix: texts in notifications for creating & created (#714,#716)

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoKubernetesClientTest.java
src/main/java/org/jboss/tools/intellij/openshift/actions/project/ChangeActiveProjectAction.java
src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java

fix:  show 'missing project' - not 'log in' - when current is inexistant (#715, #719)

---

.github/workflows/ci.yml
.github/workflows/publish_reports.yml
.github/workflows/sonar.yml
.github/workflows/ui_it.yml

chore(skip-release): reverting workflow chain

---

.github/workflows/integration_ui_tests.yml

chore(skip-release): publish UI IT test reports

---

src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliListTest.java
src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliRepoTest.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/DescriptorFactory.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/HelmRepositoriesNode.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/HelmRepositoryNode.java
src/main/java/org/jboss/tools/intellij/openshift/ui/SwingUtils.java
src/main/java/org/jboss/tools/intellij/openshift/ui/helm/ChartIcons.java
src/main/java/org/jboss/tools/intellij/openshift/utils/helm/Helm.java
src/main/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCli.java
src/main/java/org/jboss/tools/intellij/openshift/utils/helm/HelmRepository.java
src/main/resources/images/helm/repo.svg

feat: list helm repositories (#672)

---

build.gradle

fix: rm'd explicit snakeyaml dependency causing fatal IDE error (#776)

---

.github/workflows/validate_IJ_versions.yml
build.gradle
gradle.properties
src/main/resources/META-INF/plugin.xml

https://github.com/redhat-developer/intellij-common/pull/219

chore(skip-release): bump sinceIdea to IC-2022.3

---

build.gradle

fix: corrected intellij-common for test (#758)

---

gradle.properties
src/main/resources/META-INF/plugin.xml

chore(skip-release): Prepare 1.9.0

---

src/main/resources/tools.json

See https://mirror.openshift.com/pub/openshift-v4/clients/helm

fix: Update helm to 3.13.2

---

.github/workflows/ci.yml
.github/workflows/integration_ui_tests.yml

build(deps): bump helm/kind-action from 1.9.0 to 1.10.0 part two 

---

build.gradle

chore: disable telemetry during tests

---

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java

test: fix/improve services integration tests

---

src/it/java/org/jboss/tools/intellij/openshift/test/ui/junit/TestRunnerExtension.java

test: Run UI tests with IJ 2024.1

---

src/main/resources/tools.json

See https://mirror.openshift.com/pub/openshift-v4/clients/helm

fix: Update helm to 3.14.4

---

src/main/resources/tools.json

See https://github.com/redhat-developer/odo/releases/tag/v3.16.1

fix: Update odo to 3.16.1

---

src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/LoginAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/RefreshAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/helm/RefreshAction.java
src/main/resources/META-INF/plugin.xml

feat: added Refresh action for helm repositories tree node (#808)

---

src/main/java/org/jboss/tools/intellij/openshift/WindowToolFactory.java

we dont need the PopupHandlerAdapter any more since we moved >`IC-2022.1`

fix: removed usage of PopupHandlerAdapter

---

src/main/java/org/jboss/tools/intellij/openshift/WindowToolFactory.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java

fix: make sure ApplicationsRootNode is properly disposed (#868)

---

src/main/java/org/jboss/tools/intellij/openshift/telemetry/TelemetrySender.java
src/main/java/org/jboss/tools/intellij/openshift/ui/cluster/TokenExtractor.java
src/main/java/org/jboss/tools/intellij/openshift/ui/sandbox/CountryCodeValidator.java
src/main/java/org/jboss/tools/intellij/openshift/ui/sandbox/PhoneNumberValidator.java
src/main/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtils.java
src/test/java/org/jboss/tools/intellij/openshift/ui/cluster/TokenExtractorTest.java
src/test/java/org/jboss/tools/intellij/openshift/ui/sandbox/CountryCodeValidatorTest.java
src/test/java/org/jboss/tools/intellij/openshift/ui/sandbox/PhoneNumberValidatorTest.java
src/test/java/org/jboss/tools/intellij/openshift/ui/sandbox/SandboxProcessorTest.java
src/test/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtilsTest.java

fix: parse login command regexp and other regexp

---

src/test/java/org/jboss/tools/intellij/openshift/ui/cluster/TokenExtractorTest.java
src/test/java/org/jboss/tools/intellij/openshift/utils/OCCommandUtilsTest.java

fixes false positive secrets detection

chore: add false positive leak comment on tokens tests

---

src/main/java/org/jboss/tools/intellij/openshift/ui/project/CreateNewProjectDialog.java

fix: fix name validation regexp

---

src/main/java/org/jboss/tools/intellij/openshift/actions/HelmAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/helm/RemoveRepositoriesAction.java
src/main/java/org/jboss/tools/intellij/openshift/actions/helm/UninstallReleaseAction.java

fix: made sure telemetry sender is initialized (#926)

---

src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java

fix: reduced span of ReadAction to avoid possible deadlock (#944)

---

src/main/java/org/jboss/tools/intellij/openshift/actions/project/CreateProjectAction.java

fixes #963 
same problem as in https://github.com/redhat-developer/intellij-openshift-connector/pull/922#pullrequestreview-2502322942

fix: execute in BGT to avoid freezing EDT (#963)

---

.github/workflows/IJ-latest.yml
.github/workflows/validate_IJ_versions.yml
build.gradle.kts
gradle.properties
gradle/libs.versions.toml

chore: fix Latest IJ workflow
