redhat-developer/intellij-openshift-connector

src/main/java/org/jboss/tools/intellij/openshift/Constants.java
Renamed the notification group for this plugin to 'OpenShift Connector'
=> Notifications group renamed to 'OpenShift Connector'

build.gradle, gradle.properties
Changes required to build using jdk11
fixes #97
run gradle build either in intellij or command-line
=> allow running gradle build with jdk11

src/main/java/org/jboss/tools/intellij/openshift/ui/cluster/LoginDialog.form
Added ":" to the "Cluster URL" and "Token" in "Cluster login"
fixes #110 
Open "Cluster login" dialog. Look at "Cluster URL" and "Token"
=> added colons to labels for "Cluster URL", "Token" (#110)

src/main/java/org/jboss/tools/intellij/openshift/actions/application/DeleteApplicationAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/DeleteFromKubeConfigAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/DeleteComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/project/DeleteProjectAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/service/DeleteServiceAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/storage/DeleteStorageAction.java
Adds confirmation dialogs for all "Delete" actions (Kubernetes resources, Clusters)
fixes #120 
pick "Delete" on Project, Application, Service, Storage, Clusters, etc.
=> added confirmation dialogs for "Delete" actions (#120)

src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentDialogStep.form
Adds missing colons to labels in the the create form that's presented when creating a component.
fixes #114
=> Added colongs to labels in CreateComponentDialogStep (#114)

src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentDialogBinaryStep.form, src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentDialogGitStep.form
* top aligns step 2 in the "create component" wizard:
* "binary" 
* and "git" 
* adds ":" colons to labels
Steps:
1. ASSERT: have cluster with project
1. EXEC: pick "New Component" in ctx menu for the project
1. ASSERT: "Create Component" wizard shows up
1. EXEC: choose "Git" for "Source type"
Result:
Steps:
1. EXEC: choose "Binary" for "Source type"
Result:
In both forms ":" with the labels are missing and the rows should be top aligned, dropping the unused space that's in btw. the borders and btw. them
With this change, the forms look as follows:
=> added ":" to labels, top-aligned forms for create comp wiz

src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigWatcher.java, src/main/java/org/jboss/tools/intellij/openshift/utils/HighSensitivityRegistrar.java, src/test/java/org/jboss/tools/intellij/openshift/utils/HighSensitivityRegistrarTest.java
depends on #131 which has to me merged first.
Use high sensitivity when polling for filesystem changes on MacOS
(see https://bugs.openjdk.java.net/browse/JDK-7133447, https://stackoverflow.com/questions/9588737/is-java-7-watchservice-slow-for-anyone-else)
fixes #127
=> use high sensitivity watch service on MacOS (#127)

src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModel.java, src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java
depends on #136 
Adds tests to assert the refresh in ApplicationTreeModel upon changes in (the Kube-) Configuration
=> added ApplicationTreeModel tests asserting refresh upon config changes

build.gradle
According to the kotlin docs about gradle ```apply plugin``` and ```plugins { id ... }``` in gradle.build are equivalent. Read here: https://kotlinlang.org/docs/reference/using-gradle.html#targeting-the-jvm
> the plugin can be applied using the Gradle plugins DSL:
>
> `plugins {
>    id "org.jetbrains.kotlin.jvm" version "1.3.50"
> }`
>
> Alternatively, you can use the older apply plugin approach:
>
> `apply plugin: 'kotlin'`
=> gradle: replaced older 'apply plugin' by plugin ids

src/main/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceAction.java, src/main/java/org/jboss/tools/intellij/openshift/ui/service/CreateServiceDialog.form, src/main/java/org/jboss/tools/intellij/openshift/ui/service/CreateServiceDialog.java, src/test/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceActionTest.java
adding 'New service' action on project level, with application creation if needed.
fixes #153
unit tests added
Manual Tests using UI can be performed with the following scenarios :
when project is selected, new service is available as context menu and then service dialog shows with application text field editable. then if application is a new one, service is created under this application node. if application node already exists, service is created under this existing application node.
when application is selected, new service is available in context menu and then service dialog shows with application text field not editable. service is then created under the selected application.
=> #153: Create Service is not allowed at project level 

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliCatalogTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliServiceTest.java, src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/ListServicesAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceAction.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoProjectDecorator.java, src/test/java/org/jboss/tools/intellij/openshift/actions/cluster/ListComponentsActionTest.java, src/test/java/org/jboss/tools/intellij/openshift/actions/cluster/ListServicesActionTest.java, src/test/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleActionTest.java, src/test/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceActionTest.java
Services are not always available on clusters. This feature adds some checks on the action to hide/show services related actions. 
fixes #152 
Unit tests updated to take in account the service availability on clusters.
Manual test can be performed in two clusters ( one with services, one without )
=> #152: Added service catalog availability

build.gradle, src/main/java/org/jboss/tools/intellij/openshift/Constants.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
Use new version of openshift-client to determine the configMap to request to retrieve the console URL. 
fixes #119 
tested with :
- remote openshift 3.11 cluster as user
- local minishift 3.11 as user and as admin
- local crc 4.2 as user and as admin
ALL test should open the console webpage without errors
=> #119 : fix open console action

src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
using environment variables to let itest log in to a different cluster than the current context in kube config
=> Allow itests to login to arbitrary cluster

Jenkinsfile
fix release build that fails due to 2020.3 requirements to use java11
fixes #???
=> fix jenkinsFile to switch to jdk11

Jenkinsfile
Ensure Jenkins builds are auto archived and labelled when releasing
fixes #???
=> chore: auto archive Jenkins release builds

build.gradle, src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/ImportComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java, src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentDialogStep.java, src/main/java/org/jboss/tools/intellij/openshift/ui/component/CreateComponentModel.java, src/main/java/org/jboss/tools/intellij/openshift/utils/ProjectUtils.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/ComponentTypesDeserializer.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/DevfileComponentType.java
=> feat: Integrate alizer and improve create component workflow

build.gradle, src/it/java/org/jboss/tools/intellij/openshift/test/ui/AbstractBaseTest.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/BaseUITest.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/annotations/UITest.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/common/CreateComponentFixture.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/common/ImportProjectFromVersionControlFixture.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/common/ProjectTreeFixture.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/common/WelcomeDialogFixture.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/ProjectStructureDialog.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/junit/TestRunnerExtension.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/runner/IdeaRunner.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/utils/ProjectUtility.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/views/OpenshiftView.java
Signed-off-by: Ondrej Dockal <odockal@redhat.com>
fixes #???
=> feat: Introducing UI tests

README.md, gradle.properties, src/main/resources/META-INF/plugin.xml
Prepare for 1.2.0  https://github.com/redhat-developer/intellij-openshift-connector/milestone/34
=> chore(skip-release): Prepare for 1.2.0

.github/workflows/ci.yml, .github/workflows/conventionalCheck.yml, .github/workflows/publish_reports.yml, .github/workflows/release.yml
Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
This PR was submitted by a script.
=> chore: Pin 3rd-party actions to SHA1

build.gradle
Update gradle build to use latest versions of deps, as use constraints to remove some transitive exposed dependencies
fixes #541
=> chore: Update dependencies

gradle.properties, src/main/resources/META-INF/plugin.xml
Prepare for 1.4.0 https://github.com/redhat-developer/intellij-openshift-connector/milestone/36
=> chore(skip-release): Prepare for 1.4.0

gradle.properties
Prepare for 1.5.0 https://github.com/redhat-developer/intellij-openshift-connector/milestone/37
=> chore(skip-release): Prepare for 1.5.0

README.md
Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/redhatdeveloperintellijopenshiftconnector/). Built directly from source and updated on schedule. In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.
Documentation-only change. Intended to simplify developer's introduction to the project.
README.md is the only document affected
=> docs: add repository map to README.md

.github/workflows/ci.yml
Triggering job **Java CI with Gradle** using **pull_request_target** instead of pull_request.
This change is needed for correct function of GitHub secrets, which are used in #563
=> feat: Change job trigger to pull_request_target

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
related to https://github.com/redhat-developer/intellij-common/pull/203/
=> fix: refactor: use ClusterHelper#isOpenShift in commons

build.gradle, src/main/java/org/jboss/tools/intellij/openshift/actions/toolwindow/FeedBackAction.java
fixes #647
depends on https://github.com/redhat-developer/intellij-redhat-telemetry/pull/74
=> refactor: use telemetry feedback API (#647)

src/main/resources/tools.json
=> fix: corrected helm config for m1/m2 macs (#653)

build.gradle
=> fix: avoid NoSuchMethodError when using intellij-kubernetes 1.21 (#662)

.github/workflows/integration_tests.yml
=> chore(skip-release): disable integration UI tests

src/main/java/org/jboss/tools/intellij/openshift/actions/helm/OpenHelmChartsAction.java, src/main/resources/META-INF/plugin.xml, src/test/java/org/jboss/tools/intellij/openshift/actions/helm/OpenHelmChartsActionTest.java
=> fix: offer 'Open Helm Charts' on project node (was: cluster)(#676)

src/main/java/org/jboss/tools/intellij/openshift/actions/OdoAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/project/ChangeActiveProjectAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/project/CreateProjectAction.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationRootNodeOdo.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ChangeActiveProjectLinkNode.java, src/main/java/org/jboss/tools/intellij/openshift/ui/BaseDialog.java, src/main/java/org/jboss/tools/intellij/openshift/ui/SwingUtils.java, src/main/java/org/jboss/tools/intellij/openshift/ui/project/ChangeActiveProjectDialog.java, src/main/java/org/jboss/tools/intellij/openshift/ui/project/CreateNewProjectDialog.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java, src/test/java/org/jboss/tools/intellij/openshift/actions/ActionTest.java, src/test/java/org/jboss/tools/intellij/openshift/actions/project/CreateProjectActionTest.java
fixes #237, #674, #701
depends on #661
=> feat: validate new project name (#237)

src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java
=> fix: show 'no url/binding' node, use async leafstate for component (#687)

src/main/resources/schemas/devfile.json
Currently an old devfile schema is used. This leads to schema validation warnings like in the following:
This is address in this issue and the schema updated to the latest version (2.2.2): https://github.com/devfile/api/blob/v2.2.2/schemas/latest/devfile.json
no
=> chore: Update devfile schema from 2.0.0 to 2.2.2

build.gradle
fixes #758 
depends on:
* https://github.com/redhat-developer/intellij-common/issues/210 (intellij-common bumped to same kubernetes-client)
* https://github.com/redhat-developer/intellij-common/pull/220 (intellij-common 1.9.4 to be released)
=> refactor: bump openshift-client 6.12 (#758)

src/main/java/org/jboss/tools/intellij/openshift/actions/project/DeleteProjectAction.java
use Project/namespace words according to current cluster kind
fixes #708
=> fix: 'Delete Project' label is confusing when using kubernetes cluster

build.gradle, src/it/java/org/jboss/tools/intellij/openshift/utils/ToolFactoryTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java, src/main/java/org/jboss/tools/intellij/openshift/actions/HelmAction.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationRootNodeOdo.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java, src/main/java/org/jboss/tools/intellij/openshift/utils/ToolFactory.java, src/test/java/org/jboss/tools/intellij/openshift/actions/ActionTest.java, src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationRootNodeOdoTest.java
fixes #802
depends on https://github.com/redhat-developer/intellij-common/pull/228
=> fix: dont refresh tree if binary is not downloaded (#802)

build.gradle, src/it/java/org/jboss/tools/intellij/openshift/test/ui/annotations/UITest.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/views/GettingStartedView.java, src/it/java/org/jboss/tools/intellij/openshift/utils/helm/Charts.java, src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliRepoTest.java, src/main/java/org/jboss/tools/intellij/openshift/actions/helm/AddHelmRepoAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/helm/EditHelmRepoAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/helm/OpenHelmChartsAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/helm/RemoveRepositoriesAction.java, src/main/java/org/jboss/tools/intellij/openshift/ui/SwingUtils.java, src/main/java/org/jboss/tools/intellij/openshift/ui/helm/AddHelmRepoDialog.java, src/main/java/org/jboss/tools/intellij/openshift/ui/helm/ChartsDialog.java, src/main/java/org/jboss/tools/intellij/openshift/ui/helm/EditHelmRepoDialog.java, src/main/java/org/jboss/tools/intellij/openshift/utils/helm/Helm.java, src/main/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCli.java, src/main/resources/META-INF/plugin.xml, src/test/java/org/jboss/tools/intellij/openshift/actions/ActionTest.java, src/test/java/org/jboss/tools/intellij/openshift/actions/helm/AddHelmRepositoryActionTest.java, src/test/java/org/jboss/tools/intellij/openshift/actions/helm/RemoveHelmRepositoryActionTest.java
fixes #673, #803 
depends on https://github.com/redhat-developer/intellij-common/pull/226, #802
=> feat: add/remove/edit helm repo (#673, #803)

src/main/java/org/jboss/tools/intellij/openshift/actions/HelmAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/TelemetryAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/binding/DeleteBindingAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/AboutAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/LoginAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/CreateComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/DebugComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/DeleteComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/DescribeComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/FeatureComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/ImportComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/LinkServiceAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/component/ShowLogComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/helm/RefreshAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/helm/RemoveRepositoriesAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/project/CreateProjectAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/project/DeleteProjectAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/registry/CreateRegistryAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/registry/DeleteRegistryAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/service/CreateServiceAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/service/DeleteServiceAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/service/LinkComponentAction.java, src/main/java/org/jboss/tools/intellij/openshift/telemetry/TelemetryHandler.java, src/main/java/org/jboss/tools/intellij/openshift/telemetry/TelemetrySender.java
=> fix: Anonymise error messages by removing exception handling

src/main/java/org/jboss/tools/intellij/openshift/utils/odo/JSonParser.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
=> fix: Fix usage of deprecated APIs

.github/workflows/cluster_integration_ui_tests.yml, .github/workflows/public_integration_ui_tests.yml, src/it/java/org/jboss/tools/intellij/openshift/test/ui/dialogs/ClusterLoginDialog.java, src/it/java/org/jboss/tools/intellij/openshift/test/ui/views/OpenshiftView.java
Fixes #892. With my apologies I have noticed that the public tests have an instability to them, where every third or so would fail because of context menu or Login Dialog itself. I ran the test with this fix 20 or more times to verify and this fixes the instability.
=> fix(UItest): extended timeout for login dialog for test stability

src/main/java/org/jboss/tools/intellij/openshift/ui/helm/install/InstallPanel.java
=> fix: corrected widget alignements in install helm chart panel (#876)

src/main/java/org/jboss/tools/intellij/openshift/WindowToolFactory.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java, src/main/java/org/jboss/tools/intellij/openshift/utils/Cli.java, src/main/java/org/jboss/tools/intellij/openshift/utils/oc/OcCli.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java
=> fix: update tree, query cluster info and send telemetry in backgroud (#912)

src/main/java/org/jboss/tools/intellij/openshift/ui/helm/install/InstallPanel.java
=> fix: hookup 'install' button to return-key once button was created (#927)

.github/workflows/ci.yml, .github/workflows/cluster_integration_ui_tests.yml, .github/workflows/conventionalCheck.yml, .github/workflows/nightly.yml, .github/workflows/validate_IJ_versions.yml, build.gradle.kts, gradle.properties, gradle/libs.versions.toml, src/it/java/org/jboss/tools/intellij/openshift/utils/helm/Charts.java, src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliRepoTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliCatalogTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliComponentTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliProjectTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliRegistryTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliServiceTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java
see https://github.com/redhat-developer/service-binding-operator#deprecation-notice
and 404 while trying to install a compliant service (https://operatorhub.io/install/stable/cloud-native-postgresql.yaml)
=> chore: disable service tests

build.gradle.kts
This allows hot code swap when developing.
**Steps:**
1. EXEC: add a line (ex. `System.err.println("hello")` in `RefreshAction#doActionPerformed`
```java
public void doActionPerformed(ApplicationsRootNode root) {
System.err.println("hello");
if (root == null) {
return;
}
```
2. ASSERT: In the editor, you are informed that you can hot-swap the code
3. EXEC: click the bug icon to the right of the notification
**Result:**
Hot swap fails
**Steps:**
1. EXEC: change the line that you added above`RefreshAction#doActionPerformed`
2. ASSERT: In the editor, you are informed that you can hot-swap the code
1. EXEC: click the bug icon to the right of the notification
**Result:**
Hot swap succeeds
=> feat: allow hotswap in 'runIde' for >=IC-2024.1

gradle/libs.versions.toml, src/it/java/org/jboss/tools/intellij/openshift/utils/OdoCluster.java, src/it/java/org/jboss/tools/intellij/openshift/utils/ToolFactoryTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliSearchTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCliTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java, src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoKubernetesClientTest.java, src/main/java/org/jboss/tools/intellij/openshift/actions/HelmAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/OcAction.java, src/main/java/org/jboss/tools/intellij/openshift/actions/project/ChangeActiveProjectAction.java, src/main/java/org/jboss/tools/intellij/openshift/oauth/AccountService.java, src/main/java/org/jboss/tools/intellij/openshift/oauth/model/AccountModel.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java, src/main/java/org/jboss/tools/intellij/openshift/tree/application/DescriptorFactory.java, src/main/java/org/jboss/tools/intellij/openshift/utils/Cli.java, src/main/java/org/jboss/tools/intellij/openshift/utils/ClientAwareCli.java, src/main/java/org/jboss/tools/intellij/openshift/utils/ExceptionUtils.java, src/main/java/org/jboss/tools/intellij/openshift/utils/KubernetesClientFactory.java, src/main/java/org/jboss/tools/intellij/openshift/utils/ToolFactory.java, src/main/java/org/jboss/tools/intellij/openshift/utils/helm/HelmCli.java, src/main/java/org/jboss/tools/intellij/openshift/utils/oc/OcCli.java, src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java, src/test/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModelConfigUpdateTest.java
depends on merging https://github.com/redhat-developer/intellij-common/issues/247 and publishing intellij-common afterwards
fixes #921
=> fix: bump kubernetes-client to 7.0.0 (#921)

.github/workflows/validate_IJ_versions.yml, gradle.properties, src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java
=> fix: corrected deprecated usage of ModuleLister.moduleAdded (#732)

src/main/resources/META-INF/plugin.xml
=> fix: add default labels to actions in plugin.xml (#957)

gradle/libs.versions.toml
depends on https://github.com/redhat-developer/intellij-common/pull/268
=> chore(skip-release): bump intellij-common to 1.9.8

src/main/java/org/jboss/tools/intellij/openshift/oauth/model/ServersRepository.java
=> fix: load/save token in a task, avoid slow operation error (#958)
